server:
  port: 8080
  application:
    name: intern

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/intern
    username: postgres
    password: root

  flyway:
    enabled: true
    # disable clean database tables
    clean-disabled: false
    # if database is not null, please set this true, otherwise it will occur an error
    baseline-on-migrate: true
    # use it with baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:migration

  # resources messages
  messages:
    # i18n resources file path
    basename: i18n/messages

# log configuration
logging:
  level:
    com.kingland: debug
    org.springframework: warn

gen:
  # author
  author: KSC
  # default generate package name
  packageName: com.kingland.intern
  # auto remove table prefix
  autoRemovePre: true
  # table prefix
  tablePrefix: t_

mybatis:
  type-aliases-package: com.kingland.intern.domain
  mapper-locations: classpath:mybatis/*Mapper.xml