server:
  port: 8080
  application:
    name: dhrm2193

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/testdb
    username: postgres
    password: root

  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
    prefix: classpath:/public/         #configure page file path
    suffix: .html                      #configure the default page suffix

  flyway:
    enabled: true
    # disable clean database tables
    clean-disabled: false
    # if database is not null, please set this true, otherwise it will occur an error
    baseline-on-migrate: true
    # use it with baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:migration

# log configuration
logging:
  level:
    com.ruoyi: debug
    org.springframework: warn